pyporscheconnectapi/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
pyporscheconnectapi/cli.py,sha256=EUnXJjmjtn9c3iAD0T8Rg1GBVw6Qv-oxTQStGGkFWYw,6145
pyporscheconnectapi/client.py,sha256=KITg8wMiFGLHkvTEQkV0hKBPAZM5HZo0LEZmmMFBkhw,12732
pyporscheconnectapi/connection.py,sha256=udpCNr5aRIO-whBVOEm-7g5iWgGp86FvphhMbLI3szg,9879
pyporscheconnectapi/exceptions.py,sha256=Ez_D_TsafBd59LRIKRvGFv_6W9Ia425QCaClwXEke2w,1539
pyporscheconnectapi-0.0.12.dist-info/LICENSE,sha256=3wo4ylCH88NDNuSoNFaeaNCdzpQDloqsIUDQMg5FWec,1071
pyporscheconnectapi-0.0.12.dist-info/METADATA,sha256=a9I0z1pVilIUQb5HrpZ9pwlJ2v5bJHClnc0eTZezN8k,512
pyporscheconnectapi-0.0.12.dist-info/WHEEL,sha256=ewwEueio1C2XeHTvT17n8dZUJgOvyCWCt0WVNLClP9o,92
pyporscheconnectapi-0.0.12.dist-info/entry_points.txt,sha256=cq4djPuFhhopjtdIGqJ6w6vXOb6g65uLQSHnl7HAjfs,60
pyporscheconnectapi-0.0.12.dist-info/top_level.txt,sha256=YXSR3DO6I6QQ0lEQOvTts5BFIGsfOw_WtdFlD8BN4Yw,20
pyporscheconnectapi-0.0.12.dist-info/RECORD,,
